Add Lea Verou to Standards WG members
openjs-foundation/standards pull request #199
Opened 2022-11-08 20:34 UTC by LeaVerou

Per discussion with @jorydotcom

2022-11-09 07:53 UTC, ljharb approved these changes

2022-11-09 10:37 UTC, eemeli requested changes
Strong approval for the addition, but the list should be sorted by GitHub id.

2022-11-09 14:32 UTC, Eomm approved these changes

2022-11-09 20:49 UTC, eemeli approved these changes

2022-11-10 00:09 UTC, ljharb commented
Or better, a CI check?

2022-11-29 18:14 UTC, merged